### ISSUE TITLE
even with the API configured this is the problem i get

### ISSUE THREAD

**Issue by asciiterminal** [porthunter/smoof#1]
Traceback (most recent call last):
  File "smoof.py", line 42, in <module>
    print r.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Sokolcav** [comment]
same problem

**Comment by Xart3misX** [comment]
same problem

**Comment by art3mis-NYN** [comment]
any ideas on what this could be

**Comment by Xart3misX** [comment]
solved it

**Comment by Xart3misX** [comment]
46,Elks is a paid program u see 
to use it u have to have a payment method linked to ur account

**Comment by SunnyPro24** [comment]
not work

**Comment by darkhacknet** [comment]
> 46,Elks is a paid program u see to use it u have to have a payment method linked to ur account

Not working bro I just changed the API url to my nexmo one which has money chargen ! and the same error is displayed !
